version: "1.0"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      retries: 5
      start_period: 5s
    networks:
      - proposta-network
  proposta-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proposta-app
    depends_on:
      proposta-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - proposta-network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - DB_HOST=proposta-db
      - DB_PORT=5432
      - DB_NAME=propostadb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - 8080:8080
  proposta-web:
    image: matheuspieropan/proposta-web
    container_name: proposta-web
    depends_on:
      - proposta-service
    ports:
      - "80:80"
    networks:
      - proposta-network
  proposta-db:
    container_name: proposta-db
    image: postgres:latest
    environment:
      POSTGRES_DB: propostadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - proposta-network
    ports:
      - "5432:5432"
networks:
  proposta-network:
    driver: bridge